data:
  nuscenes_root: ${oc.env:NUSCENES_DATAROOT}
  version: "v1.0-mini"

model:
  api_key: ${oc.env:ANTHROPIC_API_KEY}
  version: "claude-3-opus-20240229"
  max_tokens: 1000

visualization:
  save_output: true
  plot_ground_truth: true
  max_range: 50  # meters